dbt_sample_project:
  target: raw
  outputs:
    raw:
      type: bigquery
      method: service-account
      keyfile: /workspace/.dbt/sa-key.json
      location: US
      project: earnest-beacon-455013-n6
# dataset left raw to allow for tag based selection override
      dataset: '{{env_var("DBT_DATASET")}}' 
      threads: 4 
      timeout_seconds: 360
