steps:
  - name: 'python:3.8'
    dir: 'dbt_sample_project'
    entrypoint: 'sh'
    secretEnv: ['_DBT_KEY_JSON']
    args:
      - '-c'
      - |
        set -e
        echo "Installing dbt..."
        pip install dbt-bigquery
        echo "Creating .dbt folder..."
        mkdir -p /builder/home/.dbt
        echo "Writing service account key to sa-key.json..."
        echo $_DBT_KEY_JSON > sa-key.json
        echo "Validating JSON format..."
        python -m json.tool sa-key.json > /dev/null || { echo "Invalid JSON in service account key"; exit 1; }
        ls -la sa-key.json
        echo "Writing profiles.yml..."
        cat > /builder/home/.dbt/profiles.yml << EOF
        dbt_sample_project:
          target: prod
          outputs:
            prod:
              type: bigquery
              method: service-account
              project: earnest-beacon-455013-n6
              dataset: dbt_sample_data
              keyfile: /workspace/dbt_sample_project/sa-key.json
              threads: 1
              timeout_seconds: 300
        EOF
        echo "Running dbt debug..."
        dbt debug --profiles-dir /builder/home/.dbt
        echo "Running dbt run..."
        dbt run --profiles-dir /builder/home/.dbt
availableSecrets:
  secretManager:
    - versionName: "projects/195563638104/secrets/test2/versions/latest"
      env: "_DBT_KEY_JSON"

options:
  logging: CLOUD_LOGGING_ONLY