steps:
  # Step 1: Access secret and save as file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=test2 --project=195563638104 > /workspace/dbt_sample_project/sa-key.json
        cat /workspace/dbt_sample_project/sa-key.json | head -n 3

  # Step 2: Run dbt
  - name: 'python:3.8'
    dir: 'dbt_sample_project'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -e
        echo "Installing dbt..."
        pip install dbt-bigquery
        echo "Creating .dbt folder..."
        mkdir -p /builder/home/.dbt
        
        echo "Writing profiles.yml..."
        cat > /builder/home/.dbt/profiles.yml << EOF
        dbt_sample_project:
          target: prod
          outputs:
            prod:
              type: bigquery
              method: service-account
              project: earnest-beacon-455013-n6
              dataset: dbt_sample_data
              keyfile: /workspace/dbt_sample_project/sa-key.json
              threads: 1
              timeout_seconds: 300
        EOF
        
        echo "Running dbt debug..."
        dbt debug --profiles-dir /builder/home/.dbt
        echo "Running dbt run..."
        dbt run --profiles-dir /builder/home/.dbt

options:
  logging: CLOUD_LOGGING_ONLY