steps:
  - name: 'python:3.8'
    dir: 'dbt_sample_project'
    entrypoint: 'sh'
    secretEnv: ['_DBT_KEY_JSON']
    args:
      - '-c'
      - |
        pip install dbt-bigquery
        mkdir -p /builder/home/.dbt

        echo "$_DBT_KEY_JSON" > sa-key.json

        echo "
        dbt_sample_project:
          target: prod
          outputs:
            prod:
              type: bigquery
              method: service-account
              project: earnest-beacon-455013-n6
              dataset: dbt_sample_data
              keyfile: /workspace/dbt_sample_project/sa-key.json
              threads: 1
              timeout_seconds: 300
        " > /builder/home/.dbt/profiles.yml

        dbt debug --profiles-dir /builder/home/.dbt
        dbt run --profiles-dir /builder/home/.dbt

availableSecrets:
  secretManager:
    - versionName: "projects/195563638104/secrets/test2/versions/latest"
      env: "_DBT_KEY_JSON"

options:
  logging: CLOUD_LOGGING_ONLY
