steps:
  # Install dependencies
  - name: 'python:3.8'
    args:
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'

  

  # Run dbt
  - name: 'python:3.8'
    args:
      - 'dbt'
      - 'run'
    dir: 'dbt_sample_project'
options:
  logging: CLOUD_LOGGING_ONLY
