steps:
  # Step 1: Install dbt, fetch secret, create key file & profiles.yml, run dbt
  - name: 'python:3.8'
    dir: 'dbt_sample_project'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install dbt-bigquery
        mkdir -p /builder/home/.dbt

        # Download key from Secret Manager and write to file
        gcloud secrets versions access latest --secret=test2 > sa-key.json

        # Create profiles.yml dynamically
        echo "
        dbt_sample_project:
          target: prod
          outputs:
            prod:
              type: bigquery
              method: service-account
              project: earnest-beacon-455013-n6
              dataset: dbt_sample_data
              keyfile: /workspace/dbt_sample_project/sa-key.json
              threads: 1
              timeout_seconds: 300
        " > /builder/home/.dbt/profiles.yml

        dbt run --profiles-dir /builder/home/.dbt

availableSecrets:
  secretManager:
    - versionName: "projects/earnest-beacon-455013-n6/secrets/test2/versions/latest"
      env: "DUMMY"
