steps:
  - id: "Install Deps"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get install -y git
        pip install uv
        uv venv
        uv pip install -r pyproject.toml
    volumes:
      - name: virtual_env
        path: /.venv

  - id: "Setup Auth With Drive Scope"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      echo "Setting up authentication with Drive scope..."
      # Get the current service account email
      CURRENT_SA=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")
      echo "Current service account: $CURRENT_SA"
      
      # Generate token with Drive scope
      ACCESS_TOKEN=$(gcloud auth print-access-token --impersonate-service-account=$CURRENT_SA --scopes=https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/drive.readonly)
      
      # Save the token for later steps
      echo "$ACCESS_TOKEN" > /workspace/drive_token.txt
      
      # Create a profiles override with the token
      mkdir -p /workspace/.dbt/
      
      # Create the profiles.yml file with project from substitution
      echo "Creating profiles.yml file..."
      cat > /workspace/.dbt/profiles.yml <<'EOF'
      default:
        outputs:
          dev:
            type: bigquery
            method: oauth
            project: $_GOOGLE_CLOUD_PROJECT
            dataset: dbt_dataset
            threads: 4
            timeout_seconds: 300
        target: dev
      EOF
      
      # Replace the placeholder with the actual value
      sed -i "s|\$_GOOGLE_CLOUD_PROJECT|$_GOOGLE_CLOUD_PROJECT|g" /workspace/.dbt/profiles.yml
      
      # Install jq for JSON parsing
      apt-get update -y && apt-get install -y jq
      
      # Verify the token works by testing Drive API access
      curl -s -H "Authorization: Bearer $ACCESS_TOKEN" https://www.googleapis.com/drive/v3/files?pageSize=1 | jq .
      
      # Success message
      echo "Auth setup complete. Token is saved at /workspace/drive_token.txt"

  - id: "Check ADC"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      echo "Checking ADC (Application Default Credentials)..."
      gcloud auth application-default print-access-token || echo "No ADC found"
      echo "Active account:"
      gcloud auth list
      
      # Show the token we created with Drive scope
      echo "Our custom token with Drive scope:"
      cat /workspace/drive_token.txt
      
      # Show the profiles.yml we created
      echo "Profiles.yml content:"
      cat /workspace/.dbt/profiles.yml

  - id: "debug workspace"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -R /workspace'

  - id: "DBT Check"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"
        
        # Read the token from the file created in the previous step
        export GOOGLE_OAUTH_TOKEN=$(cat /workspace/drive_token.txt)
        
        # Set profile dir
        export DBT_PROFILES_DIR=/workspace/.dbt/
        
        # Update the profiles.yml to include the token
        echo "Updating profiles.yml to include token..."
        sed -i "s/method: oauth/method: oauth\\n      token: $GOOGLE_OAUTH_TOKEN/g" /workspace/.dbt/profiles.yml
        
        dbt --version
        dbt deps
        dbt compile
        dbt debug
        dbt ls
    volumes:
      - name: virtual_env
        path: /.venv

  - id: "DBT Run Raw"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"
        
        # Read the token but we don't need to update the profiles.yml again
        export GOOGLE_OAUTH_TOKEN=$(cat /workspace/drive_token.txt)
        
        # Set profile dir
        export DBT_PROFILES_DIR=/workspace/.dbt/
        
        echo "Running dbt..."
        pwd
        dbt deps
        dbt run
    volumes:
      - name: virtual_env
        path: /.venv

options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLOUD_PROJECT: "earnest-beacon-455013-n6"
#  _DBT_DATASET: "hydrated_us"

serviceAccount: '195563638104-compute@developer.gserviceaccount.com'