steps:
  - id: "Install Deps"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get install -y git gettext-base
        pip install uv
        uv venv
        uv pip install -r pyproject.toml
    volumes:
      - name: virtual_env
        path: /.venv

  - id: "Generate Token & Build Profile"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e

        apt-get update && apt-get install -y jq curl gettext-base

        # Get active service account without variable assignment
        echo "Getting active service account..."
        gcloud auth list --filter=status:ACTIVE --format="value(account)" > /workspace/service_account.txt
        echo "Using service account: $(cat /workspace/service_account.txt)"

        echo "Project ID: $_GOOGLE_CLOUD_PROJECT"

        # Generate token without variable assignment
        echo "Generating token with Drive scope..."
        curl -s -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{
            "scope": [
              "https://www.googleapis.com/auth/bigquery",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }' \
          "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/$(cat /workspace/service_account.txt):generateAccessToken" \
          | jq -r '.accessToken' > /workspace/drive_token.txt
        
        echo "Token generated and saved."
        
        # Create profiles.yml
        mkdir -p /workspace/.dbt/
        
        # Create profiles with environment variable substitution
        echo "Creating profiles.yml..."
        echo "default:
          outputs:
            dev:
              type: bigquery
              method: oauth
              token: \"$(cat /workspace/drive_token.txt)\"
              project: \"$_GOOGLE_CLOUD_PROJECT\"
              dataset: dbt_dataset
              threads: 4
              timeout_seconds: 300
          target: dev" > /workspace/.dbt/profiles.yml
        
        echo "Profile created successfully."
        
  - id: "DBT Check"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        dbt --version
        dbt deps
        dbt debug
        dbt ls
    volumes:
      - name: virtual_env
        path: /.venv

  - id: "DBT Run"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        dbt deps
        dbt run
    volumes:
      - name: virtual_env
        path: /.venv

options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLOUD_PROJECT: "earnest-beacon-455013-n6"