steps:

  - id: "Install Deps"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get install -y git
        pip install uv
        uv venv
        uv pip install -r pyproject.toml

  - id: "Retrieve Secret"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud secrets versions access latest \
          --secret=$_SECRET_NAME \
          --project=$_PROJECT_NUMBER > /workspace/.dbt/sa-key.json

  - id: "Debug Workspace"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - 'ls -R /workspace'

  # RAW LAYER
  - id: "DBT Run Raw"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
      - 'DBT_DATASET=raw_us'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"

        dbt deps 
        dbt run --select tag:raw_us

  - id: "Save Raw Manifest"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        mkdir -p /workspace/manifest
        cp /workspace/target/manifest.json /workspace/manifest/raw_manifest.json

  # HYDRATED LAYER
  - id: "DBT Run Hydrated"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
      - 'DBT_DATASET=hydrated_us'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"

        dbt deps
        dbt snapshot --select tag:hydrated_us
        dbt run --select tag:hydrated_us

  - id: "Save Hydrated Manifest"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        cp /workspace/target/manifest.json /workspace/manifest/hydrated_manifest.json

  # SILVER LAYER (if applicable)
  - id: "DBT Run Silver"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
      - 'DBT_DATASET=silver_us'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"

        dbt deps
        dbt run --select tag:silver_us

  - id: "Save Silver Manifest"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        cp /workspace/target/manifest.json /workspace/manifest/silver_manifest.json

 
  # UPLOAD ALL MANIFESTS
  - id: "Upload All Manifests to GCS"
    name: "gcr.io/cloud-builders/gsutil"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Uploading all manifests to GCS..."
        gsutil cp /workspace/manifest/*.json gs://$_MANIFEST_BUCKET_NAME/

options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLOUD_PROJECT: "earnest-beacon-455013-n6"
  _SECRET_NAME: "test2"
  _PROJECT_NUMBER: "195563638104"
  _MANIFEST_BUCKET_NAME: "manifest_bucket6172025"
