steps:

  - id: "Install Deps"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get install -y git
        pip install uv
        uv venv
        uv pip install -r pyproject.toml
    volumes:
      - name: virtual_env
        path: /.venv
  - id: "Check ADC"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      echo "Checking ADC (Application Default Credentials)..."
      gcloud auth application-default print-access-token || echo "No ADC found"
      echo "Active account:"
      gcloud auth list

  - id: "debug workspace"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -R /workspace'

  - id: "DBT Check"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"
        dbt --version
        dbt deps
        dbt compile
        dbt debug
        dbt ls
    volumes:
      - name: virtual_env
        path: /.venv

  - id: "DBT Run Raw"
    name: "python:3.11-slim"
    entrypoint: sh
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        if [ -z "$_GOOGLE_CLOUD_PROJECT" ]; then
          echo "No project id provided. Please set the _GOOGLE_CLOUD_PROJECT substitution variable."
          exit 1
        fi
        export GOOGLE_CLOUD_PROJECT="$_GOOGLE_CLOUD_PROJECT"
        echo "Would excute here"
        pwd
        dbt deps
        dbt run
        
  
    volumes:
      - name: virtual_env
        path: /.venv

options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLOUD_PROJECT: "earnest-beacon-455013-n6"
#  _DBT_DATASET: "hydrated_us"

serviceAccount: '195563638104-compute@developer.gserviceaccount.com'