steps:
  - id: "Install Deps"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get install -y git gettext-base
        pip install uv
        uv venv
        uv pip install -r pyproject.toml
    volumes:
      - name: virtual_env
        path: /.venv

  
  - id: "DBT Check"
    name: "python:3.11-slim"
    entrypoint: "sh"
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
      - 'GOOGLE_OAUTH_TOKEN=$(cat /workspace/drive_token.txt)'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        apt-get update && apt-get install -y git
        
        # Set token as environment variable directly in the step
        export DBT_BIGQUERY_TOKEN=$(cat /workspace/drive_token.txt)
        
        echo "Checking ADC file location:"
        
        dbt --version
        echo "Contents of profiles.yml before running dbt:"
        cat /workspace/.dbt/profiles.yml
        dbt deps --profile dbt_sample_project
        dbt compile --profile dbt_sample_project
        dbt debug --profile dbt_sample_project
        dbt ls --profile dbt_sample_project
    volumes:
      - name: virtual_env
        path: /.venv
  - id: "List All Files"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
          echo "Listing files in /workspace:"
          ls -R /workspace

          echo "Listing files in home directory:"
          ls -R ~/

          echo "Listing ADC credentials if any:"
          find / -name application_default_credentials.json 2>/dev/null

  - id: "DBT Run"
    name: "python:3.11-slim"
    entrypoint: "sh"
    env:
      - 'DBT_PROFILES_DIR=/workspace/.dbt/'
      - 'GOOGLE_OAUTH_TOKEN=$(cat /workspace/drive_token.txt)'
      - 'CLOUDSDK_API_ENDPOINT_OVERRIDES_IAM=https://iam.googleapis.com/'
      - 'CLOUDSDK_AUTH_ACCESS_TOKEN_FILE=/workspace/drive_token.txt'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/.google/application_default_credentials.json'
    args:
      - "-c"
      - |
        . .venv/bin/activate
        
        # Set token as environment variable directly in the step
        export DBT_BIGQUERY_TOKEN=$(cat /workspace/drive_token.txt)
        
        # List all files for debugging
        echo "Files in workspace:"
        find /workspace -type f | sort
        
        echo "Files in current directory:"
        ls -la
        
        echo "Checking ADC file existence:"
        
        dbt deps --profile dbt_sample_project
        dbt run --profile dbt_sample_project
    volumes:
      - name: virtual_env
        path: /.venv

options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CLOUD_PROJECT: "earnest-beacon-455013-n6"