[project]
name = "thrasio-hub66"
version = "0.1.0"
description = "repo for dbt environment of transformations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "dbt-core>=1.9.4",
]